"""
This type stub file was generated by pyright.
"""

from inquirer.render.console.base import BaseConsoleRender

class Confirm(BaseConsoleRender):
    title_inline = ...
    def get_header(self):  # -> str:
        ...
    def process_input(self, pressed):  # -> None:
        ...
