"""
This type stub file was generated by pyright.
"""

from inquirer.render.console._text import Text

class Password(Text):
    def get_current_value(self): ...
    def handle_validation_error(self, error):  # -> str:
        ...
