"""
This type stub file was generated by pyright.
"""

"""
****************************************
validator_collection._decorators.py
****************************************

Defines the decorator used to prevent validator execution based on an available
environment variable.

"""

def disable_on_env(
    func,
):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """Disable the ``func`` called if its name is present in ``VALIDATORS_DISABLED``.

    :param func: The function/validator to be disabled.
    :type func: callable

    :returns: If disabled, the ``value`` (first positional argument) passed to
      ``func``. If enabled, the result of ``func``.

    """
    ...

def disable_checker_on_env(
    func,
):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | bool]:
    """Disable the ``func`` called if its name is present in ``CHECKERS_DISABLED``.

    :param func: The function/validator to be disabled.
    :type func: callable

    :returns: If disabled, ``True``. If enabled, the result of ``func``.

    """
    ...
