"""
This type stub file was generated by pyright.
"""

class EmptyValueError(ValueError):
    """Exception raised when an empty value is detected, but the validator does
    not allow for empty values.

    .. note::

      While in general, an "empty" value means a value that is falsey, for
      certain specific validators "empty" means explicitly
      :obj:`None <python:None>`.

      Please see: :doc:`Validator Reference <validators>`.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NotNoneError(ValueError):
    """Exception raised when a value of :obj:`None <python:None>` is expected,
    but a different empty value was detected.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class InvalidVariableNameError(ValueError):
    """Exception raised when a value is not a valid Python variable name.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NotADictError(ValueError):
    """Exception raised when a value is not a :class:`dict <python:dict>`.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NotJSONError(ValueError):
    """Exception raised when a value cannot be serialized/de-serialized to a JSON object.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NotJSONSchemaError(ValueError):
    """Exception raised when a schema supplied is not a valid JSON Schema.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class JSONValidationError(ValueError):
    """Exception raised when a value fails validation against a JSON Schema.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class InvalidEmailError(ValueError):
    """Exception raised when an email fails validation.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class InvalidURLError(ValueError):
    """Exception raised when a URL fails validation.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class InvalidDomainError(ValueError):
    """Exception raised when a domain fails validation.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class SlashInDomainError(InvalidDomainError):
    """Exception raised when a domain value contains a slash or backslash.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>` ->
    :class:`InvalidDomainError`

    """

    ...

class AtInDomainError(InvalidDomainError):
    """Exception raised when a domain value contains an ``@`` symbol.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>` ->
    :class:`InvalidDomainError`

    """

    ...

class ColonInDomainError(InvalidDomainError):
    """Exception raised when a domain value contains a colon (``:``).

    **INHERITS FROM:** :class:`ValueError <python:ValueError>` ->
    :class:`InvalidDomainError`

    """

    ...

class WhitespaceInDomainError(InvalidDomainError):
    """Exception raised when a domain value contains whitespace.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>` ->
    :class:`InvalidDomainError`

    """

    ...

class InvalidIPAddressError(ValueError):
    """Exception raised when a value is not a valid IP address.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class InvalidMACAddressError(ValueError):
    """Exception raised when a value is not a valid MAC address.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class InvalidMimeTypeError(ValueError):
    """Exception raised when a value is not a valid MIME type.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class CannotCoerceError(TypeError):
    """Exception raised when a value cannot be coerced to an expected type.

    **INHERITS FROM:** :class:`TypeError <python:TypeError>`

    """

    ...

class NotAnIterableError(CannotCoerceError):
    """Exception raised when a value is not an iterable.

    **INHERITS FROM:** :class:`TypeError <python:TypeError>` -> :class:`CannotCoerceError <validator_collection.errors.CannotCoerceError>`

    """

    ...

class IterationFailedError(NotAnIterableError):
    """Exception raised when a value conforms to one of Python's supported
    iterable protocols, but iterating across the object produced an unexpected
    Exception.

    **INHERITS FROM:** :class:`TypeError <python:TypeError>` -> :class:`CannotCoerceError <validator_collection.errors.CannotCoerceError>` -> :class:`NotAnIterableError <validator_collection.errors.NotAnIterableError>`

    """

    ...

class MaximumLengthError(ValueError):
    """Exception raised when a value exceeds a maximum allowed length.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class MinimumLengthError(ValueError):
    """Exception raised when a value has a lower length than the minimum allowed.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class MaximumValueError(ValueError):
    """Exception raised when a value exceeds a maximum allowed value.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class MinimumValueError(ValueError):
    """Exception raised when a value has a lower or earlier value than the minimum
    allowed.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NotAnIntegerError(ValueError):
    """Exception raised when a value is not being coerced and is not an integer type.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NegativeOffsetMismatchError(ValueError):
    """Exception raised when a negative offset is expected, but the value indicates
    a positive offset.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class PositiveOffsetMismatchError(ValueError):
    """Exception raised when a positive offset is expected, but the value indicates
    a negative offset.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class UTCOffsetError(ValueError):
    """Exception raised when the UTC offset exceeds +/- 24 hours.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class ValidatorUsageError(ValueError):
    """Exception raised when the validator was used incorrectly.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class CoercionFunctionEmptyError(ValidatorUsageError):
    """Exception raised when a coercion function was empty.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>` ->
    :class:`ValidatorUsageError`

    """

    ...

class CoercionFunctionError(ValueError):
    """Exception raised when a Coercion Function produces an
    :class:`Exception <python:Exception>`.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NotCallableError(ValueError):
    """Exception raised when a given value is not callable.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NotBytesIOError(ValueError):
    """Exception raised when a given value is not a
    :class:`BytesIO <python:io.BytesIO>` object.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NotStringIOError(ValueError):
    """Exception raised when a given value is not a
    :class:`StringIO <python:io.StringIO>` object.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class NotPathlikeError(ValueError):
    """Exception raised when a given value is not a path-like object.

    **INHERITS FROM:** :class:`ValueError <python:ValueError>`

    """

    ...

class PathExistsError(IOError):
    """Exception raised when a path does not exist.

    **INHERITS FROM:** :class:`IOError <python:IOError>`

    """

    ...

class NotAFileError(IOError):
    """Exception raised when a path is not a file.

    **INHERITS FROM:** :class:`IOError <python:IOError>`

    """

    ...

class NotADirectoryError(IOError):
    """Exception raised when a path is not a directory.

    **INHERITS FROM:** :class:`IOError <python:IOError>`

    """

    ...

class NotReadableError(IOError):
    """Exception raised when a path is not readable.

    **INHERITS FROM:** :class:`IOError <python:IOError>`
    """

    ...

class NotWriteableError(IOError):
    """Exception raised when a path is not writeable.

    **INHERITS FROM:** :class:`IOError <python:IOError>`
    """

    ...

class NotExecutableError(IOError):
    """Exception raised when a path is not executable.

    **INHERITS FROM:** :class:`IOError <python:IOError>`
    """

    ...
