"""
This type stub file was generated by pyright.
"""

from validator_collection._decorators import disable_on_env

URL_UNSAFE_CHARACTERS = ...
URL_REGEX = ...
URL_SPECIAL_IP_REGEX = ...
DOMAIN_REGEX = ...
URL_PROTOCOLS = ...
SPECIAL_USE_DOMAIN_NAMES = ...
EMAIL_REGEX = ...
VARIABLE_NAME_REGEX = ...
MAC_ADDRESS_REGEX = ...
IPV6_REGEX = ...
TIMEDELTA_REGEX = ...
MIME_TYPE_REGEX = ...

@disable_on_env
def uuid(value, allow_empty=..., **kwargs):  # -> UUID | None:
    """Validate that ``value`` is a valid :class:`UUID <python:uuid.UUID>`.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` coerced to a :class:`UUID <python:uuid.UUID>` object /
      :obj:`None <python:None>`
    :rtype: :class:`UUID <python:uuid.UUID>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` cannot be coerced to a
      :class:`UUID <python:uuid.UUID>`

    """
    ...

@disable_on_env
def string(
    value,
    allow_empty=...,
    coerce_value=...,
    minimum_length=...,
    maximum_length=...,
    whitespace_padding=...,
    **kwargs,
):  # -> bytes | str | None:
    """Validate that ``value`` is a valid string.

    :param value: The value to validate.
    :type value: :class:`str <python:str>` / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if ``value``
      is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>` if
      ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param coerce_value: If ``True``, will attempt to coerce ``value`` to a string if
      it is not already. If ``False``, will raise a :class:`ValueError` if ``value``
      is not a string. Defaults to ``False``.
    :type coerce_value: :class:`bool <python:bool>`

    :param minimum_length: If supplied, indicates the minimum number of characters
      needed to be valid.
    :type minimum_length: :class:`int <python:int>`

    :param maximum_length: If supplied, indicates the minimum number of characters
      needed to be valid.
    :type maximum_length: :class:`int <python:int>`

    :param whitespace_padding: If ``True`` and the value is below the
      ``minimum_length``, pad the value with spaces. Defaults to ``False``.
    :type whitespace_padding: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`str <python:str>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` is not a valid string and ``coerce_value``
      is ``False``
    :raises MinimumLengthError: if ``minimum_length`` is supplied and the length of
      ``value`` is less than ``minimum_length`` and ``whitespace_padding`` is
      ``False``
    :raises MaximumLengthError: if ``maximum_length`` is supplied and the length of
      ``value`` is more than the ``maximum_length``
    """
    ...

@disable_on_env
def iterable(
    value,
    allow_empty=...,
    forbid_literals=...,
    minimum_length=...,
    maximum_length=...,
    **kwargs,
):  # -> None:
    """Validate that ``value`` is a valid iterable.

    .. hint::

      This validator checks to ensure that ``value`` supports iteration using
      any of Python's three iteration protocols: the ``__getitem__`` protocol,
      the ``__iter__`` / ``next()`` protocol, or the inheritance from Python's
      `Iterable` abstract base class.

      If ``value`` supports any of these three iteration protocols, it will be
      validated. However, if iteration across ``value`` raises an unsupported
      exception, this function will raise an
      :exc:`IterationFailedError <validator_collection.errors.IterationFailedError>`

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if ``value``
      is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>` if
      ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param forbid_literals: A collection of literals that will be considered invalid
      even if they are (actually) iterable. Defaults to :class:`str <python:str>` and
      :class:`bytes <python:bytes>`.
    :type forbid_literals: iterable

    :param minimum_length: If supplied, indicates the minimum number of members
      needed to be valid.
    :type minimum_length: :class:`int <python:int>`

    :param maximum_length: If supplied, indicates the minimum number of members
      needed to be valid.
    :type maximum_length: :class:`int <python:int>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: iterable / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises NotAnIterableError: if ``value`` is not a valid iterable or
      :obj:`None <python:None>`
    :raises IterationFailedError: if ``value`` is a valid iterable, but iteration
      fails for some unexpected exception
    :raises MinimumLengthError: if ``minimum_length`` is supplied and the length of
      ``value`` is less than ``minimum_length`` and ``whitespace_padding`` is
      ``False``
    :raises MaximumLengthError: if ``maximum_length`` is supplied and the length of
      ``value`` is more than the ``maximum_length``
    """
    ...

@disable_on_env
def none(value, allow_empty=..., **kwargs):  # -> None:
    """Validate that ``value`` is :obj:`None <python:None>`.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if ``value``
      is empty but **not** :obj:`None <python:None>`. If  ``False``, raises a
      :class:`NotNoneError` if ``value`` is empty but **not**
      :obj:`None <python:None>`. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: :obj:`None <python:None>`

    :raises NotNoneError: if ``allow_empty`` is ``False`` and ``value`` is empty
      but **not** :obj:`None <python:None>` and

    """
    ...

@disable_on_env
def not_empty(value, allow_empty=..., **kwargs):  # -> None:
    """Validate that ``value`` is not empty.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    """
    ...

@disable_on_env
def variable_name(value, allow_empty=..., **kwargs):  # -> None:
    """Validate that the value is a valid Python variable name.

    .. caution::

      This function does **NOT** check whether the variable exists. It only
      checks that the ``value`` would work as a Python variable (or class, or
      function, etc.) name.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`str <python:str>` or :obj:`None <python:None>`

    :raises EmptyValueError: if ``allow_empty`` is ``False`` and ``value``
      is empty
    """
    ...

@disable_on_env
def dict(
    value, allow_empty=..., json_serializer=..., **kwargs
):  # -> dict[Any, Any] | None:
    """Validate that ``value`` is a :class:`dict <python:dict>`.

    .. hint::

      If ``value`` is a string, this validator will assume it is a JSON
      object and try to convert it into a :class:`dict <python:dict>`

      You can override the JSON serializer used by passing it to the
      ``json_serializer`` property. By default, will utilize the Python
      :class:`json <json>` encoder/decoder.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param json_serializer: The JSON encoder/decoder to use to deserialize a
      string passed in ``value``. If not supplied, will default to the Python
      :class:`json <python:json>` encoder/decoder.
    :type json_serializer: callable

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`dict <python:dict>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` cannot be coerced to a
      :class:`dict <python:dict>`
    :raises NotADictError: if ``value`` is not a :class:`dict <python:dict>`

    """
    ...

@disable_on_env
def json(
    value, schema=..., allow_empty=..., json_serializer=..., **kwargs
):  # -> list[Any] | dict_ | None:
    """Validate that ``value`` conforms to the supplied JSON Schema.

    .. note::

      ``schema`` supports JSON Schema Drafts 3 - 7. Unless the JSON Schema indicates the
      meta-schema using a ``$schema`` property, the schema will be assumed to conform to
      Draft 7.

    .. hint::

      If either ``value`` or ``schema`` is a string, this validator will assume it is a
      JSON object and try to convert it into a :class:`dict <python:dict>`.

      You can override the JSON serializer used by passing it to the
      ``json_serializer`` property. By default, will utilize the Python
      :class:`json <json>` encoder/decoder.

    :param value: The value to validate.

    :param schema: An optional JSON Schema against which ``value`` will be validated.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param json_serializer: The JSON encoder/decoder to use to deserialize a
      string passed in ``value``. If not supplied, will default to the Python
      :class:`json <python:json>` encoder/decoder.
    :type json_serializer: callable

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`dict <python:dict>` / :class:`list <python:list>` of
      :class:`dict <python:dict>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` cannot be coerced to a
      :class:`dict <python:dict>`
    :raises NotJSONError: if ``value`` cannot be deserialized from JSON
    :raises NotJSONSchemaError: if ``schema`` is not a valid JSON Schema object
    :raises JSONValidationError: if ``value`` does not validate against the JSON Schema

    """
    ...

@disable_on_env
def date(
    value, allow_empty=..., minimum=..., maximum=..., coerce_value=..., **kwargs
):  # -> _Date | datetime | int | float | Decimal | Fraction | None:
    """Validate that ``value`` is a valid date.

    :param value: The value to validate.
    :type value: :class:`str <python:str>` / :class:`datetime <python:datetime.datetime>`
      / :class:`date <python:datetime.date>` / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param minimum: If supplied, will make sure that ``value`` is on or after this value.
    :type minimum: :class:`datetime <python:datetime.datetime>` /
      :class:`date <python:datetime.date>` / compliant :class:`str <python:str>`
      / :obj:`None <python:None>`

    :param maximum: If supplied, will make sure that ``value`` is on or before this
      value.
    :type maximum: :class:`datetime <python:datetime.datetime>` /
      :class:`date <python:datetime.date>` / compliant :class:`str <python:str>`
      / :obj:`None <python:None>`

    :param coerce_value: If ``True``, will attempt to coerce ``value`` to a
      :class:`date <python:datetime.date>` if it is a timestamp value. If ``False``,
      will not.
    :type coerce_value: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`date <python:datetime.date>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` cannot be coerced to a
      :class:`date <python:datetime.date>` and is not :obj:`None <python:None>`
    :raises MinimumValueError: if ``minimum`` is supplied but ``value`` occurs before
      ``minimum``
    :raises MaximumValueError: if ``maximum`` is supplied but ``value`` occurs after
      ``maximum``

    """
    ...

@disable_on_env
def datetime(
    value, allow_empty=..., minimum=..., maximum=..., coerce_value=..., **kwargs
):
    """Validate that ``value`` is a valid datetime.

    .. caution::

      If supplying a string, the string needs to be in an ISO 8601-format to pass
      validation. If it is not in an ISO 8601-format, validation will fail.

    :param value: The value to validate.
    :type value: :class:`str <python:str>` / :class:`datetime <python:datetime.datetime>`
      / :class:`date <python:datetime.date>` / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param minimum: If supplied, will make sure that ``value`` is on or after this value.
    :type minimum: :class:`datetime <python:datetime.datetime>` /
      :class:`date <python:datetime.date>` / compliant :class:`str <python:str>` /
      :obj:`None <python:None>`

    :param maximum: If supplied, will make sure that ``value`` is on or before this
      value.
    :type maximum: :class:`datetime <python:datetime.datetime>` /
      :class:`date <python:datetime.date>` / compliant :class:`str <python:str>` /
      :obj:`None <python:None>`

    :param coerce_value: If ``True``, will coerce dates to
      :class:`datetime <python:datetime.datetime>` objects with times of 00:00:00. If ``False``, will error
      if ``value`` is not an unambiguous timestamp. Defaults to ``True``.
    :type coerce_value: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`datetime <python:datetime.datetime>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` cannot be coerced to a
      :class:`datetime <python:datetime.datetime>` value and is not
      :obj:`None <python:None>`
    :raises MinimumValueError: if ``minimum`` is supplied but ``value`` occurs
      before ``minimum``
    :raises MaximumValueError: if ``maximum`` is supplied but ``value`` occurs
      after ``minimum``

    """
    ...

@disable_on_env
def time(value, allow_empty=..., minimum=..., maximum=..., coerce_value=..., **kwargs):
    """Validate that ``value`` is a valid :class:`time <python:datetime.time>`.

    .. caution::

      This validator will **always** return the time as timezone naive (effectively
      UTC). If ``value`` has a timezone / UTC offset applied, the validator will
      coerce the value returned back to UTC.

    :param value: The value to validate.
    :type value: :func:`datetime <validator_collection.validators.datetime>` or
      :func:`time <validator_collection.validators.time>`-compliant
      :class:`str <python:str>` / :class:`datetime <python:datetime.datetime>` /
      :class:`time <python:datetime.time> / numeric / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param minimum: If supplied, will make sure that ``value`` is on or after this value.
    :type minimum: :func:`datetime <validator_collection.validators.datetime>` or
      :func:`time <validator_collection.validators.time>`-compliant
      :class:`str <python:str>` / :class:`datetime <python:datetime.datetime>` /
      :class:`time <python:datetime.time> / numeric / :obj:`None <python:None>`

    :param maximum: If supplied, will make sure that ``value`` is on or before this
      value.
    :type maximum: :func:`datetime <validator_collection.validators.datetime>` or
      :func:`time <validator_collection.validators.time>`-compliant
      :class:`str <python:str>` / :class:`datetime <python:datetime.datetime>` /
      :class:`time <python:datetime.time> / numeric / :obj:`None <python:None>`

    :param coerce_value: If ``True``, will attempt to coerce/extract a
      :class:`time <python:datetime.time>` from ``value``. If ``False``, will only
      respect direct representations of time. Defaults to ``True``.
    :type coerce_value: :class:`bool <python:bool>`

    :returns: ``value`` in UTC time / :obj:`None <python:None>`
    :rtype: :class:`time <python:datetime.time>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` cannot be coerced to a
      :class:`time <python:datetime.time>` and is not :obj:`None <python:None>`
    :raises MinimumValueError: if ``minimum`` is supplied but ``value`` occurs
      before ``minimum``
    :raises MaximumValueError: if ``maximum`` is supplied but ``value`` occurs
      after ``minimum``

    """
    ...

@disable_on_env
def timezone(
    value, allow_empty=..., positive=..., **kwargs
):  # -> _TzInfo | TimeZone | None:
    """Validate that ``value`` is a valid :class:`tzinfo <python:datetime.tzinfo>`.

    .. caution::

      This does **not** verify whether the value is a timezone that actually
      exists, nor can it resolve timezone names (e.g. ``'Eastern'`` or ``'CET'``).

      For that kind of functionality, we recommend you utilize:
      `pytz <https://pypi.python.org/pypi/pytz>`_

    :param value: The value to validate.
    :type value: :class:`str <python:str>` / :class:`tzinfo <python:datetime.tzinfo>`
      / numeric / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param positive: Indicates whether the ``value`` is positive or negative
      (only has meaning if ``value`` is a string). Defaults to ``True``.
    :type positive: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`tzinfo <python:datetime.tzinfo>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` cannot be coerced to
      :class:`tzinfo <python:datetime.tzinfo>` and is not :obj:`None <python:None>`
    :raises PositiveOffsetMismatchError: if ``positive`` is ``True``, but the offset
      indicated by ``value`` is actually negative
    :raises NegativeOffsetMismatchError: if ``positive`` is ``False``, but the offset
      indicated by ``value`` is actually positive

    """
    ...

@disable_on_env
def timedelta(value, allow_empty=..., resolution=..., **kwargs):  # -> timedelta | None:
    """Validate that ``value`` is a valid :class:`timedelta <python:datetime.timedelta>`.

    .. note::

      Expects to receive a value that is either a
      :class:`timedelta <python:datetime.timedelta>`, a numeric value that can
      be coerced to a :class:`timedelta <python:datetime.timedelta>`, or a
      string that can be coerced to a :class:`timedelta <python:datetime.timedelta>`.
      Coerceable string formats are:

        * HH:MM:SS
        * X day, HH:MM:SS
        * X days, HH:MM:SS
        * HH:MM:SS.us
        * X day, HH:MM:SS.us
        * X days, HH:MM:SS.us

      where "us" refer to microseconds. Shout out to Alex Pitchford for sharing the
      `string-parsing regex <http://kbyanc.blogspot.com/2007/08/python-reconstructing-timedeltas-from.html?showComment=1452111163905#c3907051065256615667>`_.

    :param value: The value to validate. Accepts either a numeric value indicating
      a number of seconds or a string indicating an amount of time.
    :type value: :class:`str <python:str>` / :class:`timedelta <python:datetime.timedelta>`
      / numeric / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param resolution: Indicates the time period resolution represented by ``value``.
      Accepts ``'years'``, ``'weeks'``, ``'days'``, ``'hours'``, ``'minutes'``,
      ``'seconds'``, ``'milliseconds'``, or ``'microseconds'``. Defaults to
      ``'seconds'``.
    :type resolution: :class:`str <python:str>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`timedelta <python:datetime.timedelta>` / :obj:`None <python:None>`

    :raises ValueError: if ``resolution`` is not a valid time period resolution
    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` cannot be coerced to
      :class:`timedelta <python:datetime.timedelta>` and is not :obj:`None <python:None>`

    """
    ...

@disable_on_env
def numeric(
    value, allow_empty=..., minimum=..., maximum=..., **kwargs
):  # -> float | int | Decimal | Fraction:
    """Validate that ``value`` is a numeric value.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if ``value``
      is :obj:`None <python:None>`. If ``False``, raises an
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>` if
      ``value`` is :obj:`None <python:None>`.
      Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param minimum: If supplied, will make sure that ``value`` is greater than or
      equal to this value.
    :type minimum: numeric

    :param maximum: If supplied, will make sure that ``value`` is less than or
      equal to this value.
    :type maximum: numeric

    :returns: ``value`` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is :obj:`None <python:None>` and
      ``allow_empty`` is ``False``
    :raises MinimumValueError: if ``minimum`` is supplied and ``value`` is less
      than the ``minimum``
    :raises MaximumValueError: if ``maximum`` is supplied and ``value`` is more
      than the ``maximum``
    :raises CannotCoerceError: if ``value`` cannot be coerced to a numeric form

    """
    ...

@disable_on_env
def integer(
    value,
    allow_empty=...,
    coerce_value=...,
    minimum=...,
    maximum=...,
    base=...,
    **kwargs,
):  # -> int:
    """Validate that ``value`` is an :class:`int <python:int>`.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is :obj:`None <python:None>`. If  ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>` if
      ``value`` is :obj:`None <python:None>`.
      Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param coerce_value: If ``True``, will force any numeric ``value`` to an integer
      (always rounding up). If ``False``, will raise an error if ``value`` is numeric
      but not a whole number. Defaults to ``False``.
    :type coerce_value: :class:`bool <python:bool>`

    :param minimum: If supplied, will make sure that ``value`` is greater than or
      equal to this value.
    :type minimum: numeric

    :param maximum: If supplied, will make sure that ``value`` is less than or
      equal to this value.
    :type maximum: numeric

    :param base: Indicates the base that is used to determine the integer value.
      The allowed values are 0 and 2–36. Base-2, -8, and -16 literals can be
      optionally prefixed with ``0b/0B``, ``0o/0O/0``, or ``0x/0X``, as with
      integer literals in code. Base 0 means to interpret the string exactly as
      an integer literal, so that the actual base is 2, 8, 10, or 16. Defaults to
      ``10``.

    :returns: ``value`` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is :obj:`None <python:None>` and
      ``allow_empty`` is ``False``
    :raises MinimumValueError: if ``minimum`` is supplied and ``value`` is less
      than the ``minimum``
    :raises MaximumValueError: if ``maximum`` is supplied and ``value`` is more
      than the ``maximum``
    :raises NotAnIntegerError: if ``coerce_value`` is ``False``, and ``value``
      is not an integer
    :raises CannotCoerceError: if ``value`` cannot be coerced to an
      :class:`int <python:int>`

    """
    ...

@disable_on_env
def float(value, allow_empty=..., minimum=..., maximum=..., **kwargs):  # -> float:
    """Validate that ``value`` is a :class:`float <python:float>`.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is :obj:`None <python:None>`. If  ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>` if
      ``value`` is :obj:`None <python:None>`. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`float <python:float>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is :obj:`None <python:None>` and
      ``allow_empty`` is ``False``
    :raises MinimumValueError: if ``minimum`` is supplied and ``value`` is less
      than the ``minimum``
    :raises MaximumValueError: if ``maximum`` is supplied and ``value`` is more
      than the ``maximum``
    :raises CannotCoerceError: if unable to coerce ``value`` to a
      :class:`float <python:float>`

    """
    ...

@disable_on_env
def fraction(
    value, allow_empty=..., minimum=..., maximum=..., **kwargs
):  # -> Fraction:
    """Validate that ``value`` is a :class:`Fraction <python:fractions.Fraction>`.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if ``value``
      is :obj:`None <python:None>`. If  ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>` if
      ``value`` is :obj:`None <python:None>`. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`Fraction <python:fractions.Fraction>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is :obj:`None <python:None>` and
      ``allow_empty`` is ``False``
    :raises MinimumValueError: if ``minimum`` is supplied and ``value`` is less
      than the ``minimum``
    :raises MaximumValueError: if ``maximum`` is supplied and ``value`` is more
      than the ``maximum``
    :raises CannotCoerceError: if unable to coerce ``value`` to a
      :class:`Fraction <python:fractions.Fraction>`

    """
    ...

@disable_on_env
def decimal(
    value, allow_empty=..., minimum=..., maximum=..., **kwargs
):  # -> Decimal | None:
    """Validate that ``value`` is a :class:`Decimal <python:decimal.Decimal>`.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if ``value``
      is :obj:`None <python:None>`. If  ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>` if
      ``value`` is :obj:`None <python:None>`. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param minimum: If supplied, will make sure that ``value`` is greater than or
      equal to this value.
    :type minimum: numeric

    :param maximum: If supplied, will make sure that ``value`` is less than or
      equal to this value.
    :type maximum: numeric

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`Decimal <python:decimal.Decimal>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is :obj:`None <python:None>` and
      ``allow_empty`` is ``False``
    :raises MinimumValueError: if ``minimum`` is supplied and ``value`` is less than the
      ``minimum``
    :raises MaximumValueError: if ``maximum`` is supplied and ``value`` is more than the
      ``maximum``
    :raises CannotCoerceError: if unable to coerce ``value`` to a
      :class:`Decimal <python:decimal.Decimal>`

    """
    ...

@disable_on_env
def bytesIO(value, allow_empty=..., **kwargs):  # -> BytesIO | None:
    """Validate that ``value`` is a :class:`BytesIO <python:io.BytesIO>` object.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`BytesIO <python:io.BytesIO>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises NotBytesIOError: if ``value`` is not a :class:`BytesIO <python:io.BytesIO>`
      object.
    """
    ...

@disable_on_env
def stringIO(value, allow_empty=..., **kwargs):  # -> StringIO | None:
    """Validate that ``value`` is a :class:`StringIO <python:io.StringIO>` object.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`StringIO <python:io.StringIO>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises NotStringIOError: if ``value`` is not a :class:`StringIO <python:io.StringIO>`
      object
    """
    ...

@disable_on_env
def path(
    value, allow_empty=..., **kwargs
):  # -> str | bytes | int | PathLike[Any] | None:
    """Validate that ``value`` is a valid path-like object.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: The path represented by ``value``.
    :rtype: Path-like object / :obj:`None <python:None>`

    :raises EmptyValueError: if ``allow_empty`` is ``False`` and ``value`` is empty
    :raises NotPathlikeError: if ``value`` is not a valid path-like object

    """
    ...

@disable_on_env
def path_exists(
    value, allow_empty=..., **kwargs
):  # -> str | bytes | int | PathLike[Any] | None:
    """Validate that ``value`` is a path-like object that exists on the local
    filesystem.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: The file name represented by ``value``.
    :rtype: Path-like object / :obj:`None <python:None>`

    :raises EmptyValueError: if ``allow_empty`` is ``False`` and ``value``
      is empty
    :raises NotPathlikeError: if ``value`` is not a path-like object
    :raises PathExistsError: if ``value`` does not exist

    """
    ...

@disable_on_env
def file_exists(
    value, allow_empty=..., **kwargs
):  # -> str | bytes | int | PathLike[Any] | None:
    """Validate that ``value`` is a valid file that exists on the local filesystem.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: The file name represented by ``value``.
    :rtype: Path-like object / :obj:`None <python:None>`

    :raises EmptyValueError: if ``allow_empty`` is ``False`` and ``value``
      is empty
    :raises NotPathlikeError: if ``value`` is not a path-like object
    :raises PathExistsError: if ``value`` does not exist on the local filesystem
    :raises NotAFileError: if ``value`` is not a valid file

    """
    ...

@disable_on_env
def directory_exists(
    value, allow_empty=..., **kwargs
):  # -> str | bytes | int | PathLike[Any] | None:
    """Validate that ``value`` is a valid directory that exists on the local
    filesystem.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: The file name represented by ``value``.
    :rtype: Path-like object / :obj:`None <python:None>`

    :raises EmptyValueError: if ``allow_empty`` is ``False`` and ``value``
      is empty
    :raises NotPathlikeError: if ``value`` is not a path-like object
    :raises PathExistsError: if ``value`` does not exist on the local filesystem
    :raises NotADirectoryError: if ``value`` is not a valid directory

    """
    ...

@disable_on_env
def readable(
    value, allow_empty=..., **kwargs
):  # -> str | bytes | int | PathLike[Any] | None:
    """Validate that ``value`` is a path to a readable file.

    .. caution::

      **Use of this validator is an anti-pattern and should be used with caution.**

      Validating the readability of a file *before* attempting to read it
      exposes your code to a bug called
      `TOCTOU <https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use>`_.

      This particular class of bug can expose your code to **security vulnerabilities**
      and so this validator should only be used if you are an advanced user.

      A better pattern to use when reading from a file is to apply the principle of
      EAFP ("easier to ask forgiveness than permission"), and simply attempt to
      write to the file using a ``try ... except`` block:

      .. code-block:: python

        try:
            with open('path/to/filename.txt', mode = 'r') as file_object:
                # read from file here
        except (OSError, IOError) as error:
            # Handle an error if unable to write.

    :param value: The path to a file on the local filesystem whose readability
      is to be validated.
    :type value: Path-like object

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: Validated path-like object or :obj:`None <python:None>`
    :rtype: Path-like object or :obj:`None <python:None>`

    :raises EmptyValueError: if ``allow_empty`` is ``False`` and ``value``
      is empty
    :raises NotPathlikeError: if ``value`` is not a path-like object
    :raises PathExistsError: if ``value`` does not exist on the local filesystem
    :raises NotAFileError: if ``value`` is not a valid file
    :raises NotReadableError: if ``value`` cannot be opened for reading

    """
    ...

@disable_on_env
def writeable(
    value, allow_empty=..., **kwargs
):  # -> str | bytes | int | PathLike[Any] | None:
    """Validate that ``value`` is a path to a writeable file.

    .. caution::

      This validator does **NOT** work correctly on a Windows file system. This
      is due to the vagaries of how Windows manages its file system and the
      various ways in which it can manage file permission.

      If called on a Windows file system, this validator will raise
      :class:`NotImplementedError() <python:NotImplementedError>`.

    .. caution::

      **Use of this validator is an anti-pattern and should be used with caution.**

      Validating the writability of a file *before* attempting to write to it
      exposes your code to a bug called
      `TOCTOU <https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use>`_.

      This particular class of bug can expose your code to **security vulnerabilities**
      and so this validator should only be used if you are an advanced user.

      A better pattern to use when writing to file is to apply the principle of
      EAFP ("easier to ask forgiveness than permission"), and simply attempt to
      write to the file using a ``try ... except`` block:

      .. code-block:: python

        try:
            with open('path/to/filename.txt', mode = 'a') as file_object:
                # write to file here
        except (OSError, IOError) as error:
            # Handle an error if unable to write.

    .. note::

      This validator relies on :func:`os.access() <python:os.access>` to check
      whether ``value`` is writeable. This function has certain limitations,
      most especially that:

      * It will **ignore** file-locking (yielding a false-positive) if the file
        is locked.
      * It focuses on *local operating system permissions*, which means if trying
        to access a path over a network you might get a false positive or false
        negative (because network paths may have more complicated authentication
        methods).

    :param value: The path to a file on the local filesystem whose writeability
      is to be validated.
    :type value: Path-like object

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: Validated absolute path or :obj:`None <python:None>`
    :rtype: Path-like object or :obj:`None <python:None>`

    :raises EmptyValueError: if ``allow_empty`` is ``False`` and ``value``
      is empty
    :raises NotImplementedError: if used on a Windows system
    :raises NotPathlikeError: if ``value`` is not a path-like object
    :raises NotWriteableError: if ``value`` cannot be opened for writing

    """
    ...

@disable_on_env
def executable(
    value, allow_empty=..., **kwargs
):  # -> str | bytes | int | PathLike[Any] | None:
    """Validate that ``value`` is a path to an executable file.

    .. caution::

      This validator does **NOT** work correctly on a Windows file system. This
      is due to the vagaries of how Windows manages its file system and the
      various ways in which it can manage file permission.

      If called on a Windows file system, this validator will raise
      :class:`NotImplementedError() <python:NotImplementedError>`.

    .. caution::

      **Use of this validator is an anti-pattern and should be used with caution.**

      Validating the executability of a file *before* attempting to execute it
      exposes your code to a bug called
      `TOCTOU <https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use>`_.

      This particular class of bug can expose your code to **security vulnerabilities**
      and so this validator should only be used if you are an advanced user.

      A better pattern to use when writing to file is to apply the principle of
      EAFP ("easier to ask forgiveness than permission"), and simply attempt to
      execute the file using a ``try ... except`` block.

    .. note::

      This validator relies on :func:`os.access() <python:os.access>` to check
      whether ``value`` is executable. This function has certain limitations,
      most especially that:

      * It will **ignore** file-locking (yielding a false-positive) if the file
        is locked.
      * It focuses on *local operating system permissions*, which means if trying
        to access a path over a network you might get a false positive or false
        negative (because network paths may have more complicated authentication
        methods).

    :param value: The path to a file on the local filesystem whose writeability
      is to be validated.
    :type value: Path-like object

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: Validated absolute path or :obj:`None <python:None>`
    :rtype: Path-like object or :obj:`None <python:None>`

    :raises EmptyValueError: if ``allow_empty`` is ``False`` and ``value``
      is empty
    :raises NotImplementedError: if used on a Windows system
    :raises NotPathlikeError: if ``value`` is not a path-like object
    :raises NotAFileError: if ``value`` does not exist on the local file system
    :raises NotExecutableError: if ``value`` cannot be executed

    """
    ...

@disable_on_env
def email(value, allow_empty=..., **kwargs):  # -> bytes | str | None:
    """Validate that ``value`` is a valid email address.

    .. note::

      Email address validation is...complicated. The methodology that we have
      adopted here is *generally* compliant with
      `RFC 5322 <https://tools.ietf.org/html/rfc5322>`_ and uses a combination of
      string parsing and regular expressions.

      String parsing in particular is used to validate certain *highly unusual*
      but still valid email patterns, including the use of escaped text and
      comments within an email address' local address (the user name part).

      This approach ensures more complete coverage for unusual edge cases, while
      still letting us use regular expressions that perform quickly.

    :param value: The value to validate.
    :type value: :class:`str <python:str>` / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`str <python:str>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` is not a :class:`str <python:str>` or
      :obj:`None <python:None>`
    :raises InvalidEmailError: if ``value`` is not a valid email address or
      empty with ``allow_empty`` set to ``True``
    """
    ...

@disable_on_env
def url(
    value, allow_empty=..., allow_special_ips=..., **kwargs
):  # -> str | bytes | None:
    """Validate that ``value`` is a valid URL.

    .. note::

      URL validation is...complicated. The methodology that we have
      adopted here is *generally* compliant with
      `RFC 1738 <https://tools.ietf.org/html/rfc1738>`_,
      `RFC 6761 <https://tools.ietf.org/html/rfc6761>`_,
      `RFC 2181 <https://tools.ietf.org/html/rfc2181>`_  and uses a combination of
      string parsing and regular expressions,

      This approach ensures more complete coverage for unusual edge cases, while
      still letting us use regular expressions that perform quickly.

    :param value: The value to validate.
    :type value: :class:`str <python:str>` / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param allow_special_ips: If ``True``, will succeed when validating special IP
      addresses, such as loopback IPs like ``127.0.0.1`` or ``0.0.0.0``. If ``False``,
      will raise a :class:`InvalidURLError` if ``value`` is a special IP address. Defaults
      to ``False``.
    :type allow_special_ips: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`str <python:str>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` is not a :class:`str <python:str>` or
      :obj:`None <python:None>`
    :raises InvalidURLError: if ``value`` is not a valid URL or
      empty with ``allow_empty`` set to ``True``

    """
    ...

@disable_on_env
def domain(value, allow_empty=..., allow_ips=..., **kwargs):  # -> bytes | str | None:
    """Validate that ``value`` is a valid domain name.

    .. caution::

      This validator does not verify that ``value`` **exists** as a domain. It
      merely verifies that its contents *might* exist as a domain.

    .. note::

      This validator checks to validate that ``value`` resembles a valid
      domain name. It is - generally - compliant with
      `RFC 1035 <https://tools.ietf.org/html/rfc1035>`_ and
      `RFC 6761 <https://tools.ietf.org/html/rfc6761>`_, however it diverges
      in a number of key ways:

        * Including authentication (e.g. ``username:password@domain.dev``) will
          fail validation.
        * Including a path (e.g. ``domain.dev/path/to/file``) will fail validation.
        * Including a port (e.g. ``domain.dev:8080``) will fail validation.

      If you are hoping to validate a more complete URL, we recommend that you
      see :func:`url <validator_collection.validators.url>`.

    .. hint::

      Leading and trailing whitespace will be automatically stripped.

    :param value: The value to validate.
    :type value: :class:`str <python:str>` / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :param allow_ips: If ``True``, will succeed when validating IP addresses,
      If ``False``, will raise a :class:`InvalidDomainError` if ``value`` is an IP
      address. Defaults to ``False``.
    :type allow_ips: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`str <python:str>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` is not a :class:`str <python:str>` or
      :obj:`None <python:None>`
    :raises InvalidDomainError: if ``value`` is not a valid domain name or
      empty with ``allow_empty`` set to ``True``
    :raises SlashInDomainError: if ``value`` contains a slash or backslash
    :raises AtInDomainError: if ``value`` contains an ``@`` symbol
    :raises ColonInDomainError: if ``value`` contains a ``:`` symbol
    :raises WhitespaceInDomainError: if ``value`` contains whitespace

    """
    ...

@disable_on_env
def ip_address(value, allow_empty=..., **kwargs):  # -> str | None:
    """Validate that ``value`` is a valid IP address.

    .. note::

      First, the validator will check if the address is a valid IPv6 address.
      If that doesn't work, the validator will check if the address is a valid
      IPv4 address.

      If neither works, the validator will raise an error (as always).

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises InvalidIPAddressError: if ``value`` is not a valid IP address or empty with
      ``allow_empty`` set to ``True``

    """
    ...

@disable_on_env
def ipv4(value, allow_empty=...):  # -> None:
    """Validate that ``value`` is a valid IP version 4 address.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises InvalidIPAddressError: if ``value`` is not a valid IP version 4 address or
      empty with ``allow_empty`` set to ``True``
    """
    ...

@disable_on_env
def ipv6(value, allow_empty=..., **kwargs):  # -> str | None:
    """Validate that ``value`` is a valid IP address version 6.

    :param value: The value to validate.

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises InvalidIPAddressError: if ``value`` is not a valid IP version 6 address or
      empty with ``allow_empty`` is not set to ``True``

    """
    ...

@disable_on_env
def mac_address(value, allow_empty=..., **kwargs):  # -> bytes | str | None:
    """Validate that ``value`` is a valid MAC address.

    :param value: The value to validate.
    :type value: :class:`str <python:str>` / :obj:`None <python:None>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`str <python:str>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` is not a valid :class:`str <python:str>`
      or string-like object
    :raises InvalidMACAddressError: if ``value`` is not a valid MAC address or empty with
      ``allow_empty`` set to ``True``

    """
    ...

@disable_on_env
def mimetype(value, allow_empty=..., **kwargs):  # -> bytes | str | None:
    """Validate that ``value`` is a valid MIME-type.

    :param value: The value to validate.
    :type value: :class:`str <python:str>`

    :param allow_empty: If ``True``, returns :obj:`None <python:None>` if
      ``value`` is empty. If ``False``, raises a
      :class:`EmptyValueError <validator_collection.errors.EmptyValueError>`
      if ``value`` is empty. Defaults to ``False``.
    :type allow_empty: :class:`bool <python:bool>`

    :returns: ``value`` / :obj:`None <python:None>`
    :rtype: :class:`str <python:str>` / :obj:`None <python:None>`

    :raises EmptyValueError: if ``value`` is empty and ``allow_empty`` is ``False``
    :raises CannotCoerceError: if ``value`` is not a valid string
    :raises InvalidMimeTypeError: if ``value`` is neither a valid MIME type nor empty
      with ``allow_empty`` set to ``True``

    """
    ...
