"""
This type stub file was generated by pyright.
"""

from inquirer.render.console import ConsoleRender
from .ncourses import CoursesRender

class Render:
    def __init__(self, impl=...) -> None: ...
    def render(self, question, answers):  # -> Any:
        ...
